name: Release
#on:
#  push:
#    branches:
#      - main
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'
      - run: flutter pub get
      - run: flutter build apk
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: push and release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk, build/ios/iphoneos/app.ipa"
          tag: v2.0.3
          #          tag: v2.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}